config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  resources :users do
    resource :profile
    member do
      put :approve
      put :remove
    end
  end
  
  get 'friends', to: 'users#friends'
  
  resources :projects  
  
  resources :skills, except: [:destroy]
  
  resources :categories, except: [:destroy]
  
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
  has_many :projects, dependent: :destroy
  
  has_many :friendships
  has_many :friends, through: :friendships
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find( params[:id])
    @user_projects = @user.projects.paginate(page: params[:page], per_page: 3)
  end
  
  def index
    @users = User.includes(:profile).paginate(page: params[:page], per_page: 5)
  end
  
  def friends
    
  end
  

  def approve
    @user = User.find( params[:id])
    if @user.update(admin: true)
      flash[:success] = "User has been upgraded to Admin status"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Unable to upgrade user to Admin status"
      redirect_to root_path
    end
  end
  
  def remove
    @user = User.find( params[:id])
    if @user.update(admin: false)
      flash[:success] = "User no longer has Admin status"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Unable to remove Admin status"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def skill_icon
    if @user.profile.skills == "Graphic Designer"
      "<i class='fa fa-paint-brush'></i>".html_safe
    elsif @user.profile.skills == "Web Developer"
      "<i class='fa fa-laptop'></i>".html_safe
    elsif @user.profile.skills == "App Developer"
      "<i class='fa fa-mobile-phone'></i>".html_safe
    elsif @user.profile.skills == "Entrepreneur"
      "<i class='fa fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.skills == "Investor"
      "<i class='fa fa fa-dollar'></i>".html_safe
    elsif @user.profile.skills == "Media"
      "<i class='fa fa-pencil'></i>".html_safe
    end
  end
end

app/views/users/friends.html.erb
<h1>My Friends</h1>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">The Community</h1>
      <p class="text-center">Welcome to the OpenSauce community. Users must have a profile in order to be visible to the community</p>
      <div align="center">
        <%= will_paginate %>
      </div>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
          <% if user.profile %>
            <li>
              <div class="well row <%= cycle('white-bg', '') %>">
                <div class="col-sm-4 text-center">
                  <% if user.profile.avatar %>
                    <%= link_to user do %>
                      <%= image_tag user.profile.avatar, class: 'user-index-avatar' %>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <%= link_to user do %>
                    <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                  <% end %>
                </div>
                <small><%= pluralize(user.projects.count, "project") if user.projects %></small> </br>
                <% if user_signed_in? and current_user.admin? %>
                </br>
                <%= link_to "Delete this user", user_path(user), method: :delete, 
                                                    data: {confirm: "Are you sure you want to delete the user and all their projects" }, class: "btn btn-default btn-danger" %>
                <% end %>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
      <div align="center">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="well user-profile-block">
    <div class="row">
      <div class="col-md-3 text-center">
        <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
        </br>
        </br>
        <% if (@user == current_user || current_user.admin?) %>
          <%= link_to "Edit Profile", edit_user_profile_path(user_id: @user.id) %>
          </br>
          <%= link_to "Security Settings", edit_user_registration_path %>
          <% if current_user.admin? and !@user.admin? %>
            </br>
            <span class="approve-admin">
              <%= link_to "Upgade to Admin", approve_user_path(@user), method: :put, remote: true %>
            </span>
          <% else %>
            </br>
            <span class="approve-admin">
              <%= link_to "Remove Admin", remove_user_path(@user), method: :put, remote: true %>
            </span>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-6">
        <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
        <%#= skills will be listed here %>
        <div class="well profile-block profile-description">
          <h3>Description</h3>
          <%= @user.profile.description %>
        </div>
        <div class="well profile-block profile-description">
          <h3>Projects</h3>
          <% if @user.projects.count > 0 %>
            <div align="center">
              <%= will_paginate @user_projects %>
            </div>
            <% @user_projects.each do |project| %>
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                  <div class="well">
                    <div class="project-title">
                      <%= link_to project.title, project_path(project) %>
                    </div>
                    <div class="project-meta-details">
                      <%= truncate(project.plan, length: 100) %>
                    </div>
                    <div class="project-meta-details">
                      <small>Created by: <%= project.user.profile.first_name if project.user%>,
                      <%= time_ago_in_words(project.created_at) %> ago,
                      last updated: <%= time_ago_in_words(project.updated_at) %> ago</small>
                    </div>
                    <% if user_signed_in? && (current_user == project.user || current_user.admin?) %>
                      <div class="project-actions">
                        <%= link_to 'Edit this project', edit_project_path(project), class: 'btn btn-xs btn-primary' %>
                        <%= link_to 'Delete this project', project_path(project), method: :delete, 
                                                data: {confirm: "Are you sure you want to delete the project?"}, 
                                                class: 'btn btn-xs btn-danger' %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div align="center">
              <%= will_paginate @user_projects %>
            </div>
          <% else %>
            <p class="text-center">This user has no projects.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>