config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  resources :users do
    resource :profile
    member do
      put :approve
      put :remove
    end
  end
  
  get 'friends', to: 'users#friends'
  
  resources :projects  
  
  resources :skills, except: [:destroy]
  
  resources :categories, except: [:destroy]
  
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  
end

app/views/pages/about.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 ">
      <h1>About Page</h1>
      <p>We focus on collectively creating business ideas we'd like to see become a reality! Check out the projects below that are now up and running</p>      
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <% if user_signed_in? && current_user.profile %>
    <h1>Welcome to OpenSauce, <%= "#{current_user.profile.first_name}" %></h1>
    <h3>If you conceptualise it, they will come...</h3>
  <% else %>
    <h1>Welcome to OpenSauce</h1>
    <h3>If you conceptualise it, they will come...</h3>
  <% end %>
</div>
</br>
<% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <% if current_user.profile %>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">View Your Profile</h2>
            <%= link_to "View Your Profile", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Edit Your Profile</h2>
            <%= link_to "Edit Your Profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
      <% else %>
        <div class"col-md-12">
          <div class="well">
            <h2 class="text-center">Create Your Profile</h2>
            <h4 class="text-center">This will help others in the community find you based on your skills </h4>
            <%= link_to "Create Your Profile", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">The Community</h2>
          <h4 class="text-center">Visit the community to meet like-minded individuals to work with!</h4>
          </br>            
          <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
        </div>
      </div>
      <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">View projects</h2>
            <h4 class="text-center">See what you can contribute to the community's ideas!</h4>
            </br>
            <%= link_to "Inspire me", "#", class: 'btn btn-default btn-lg btn-block' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="well">
          <h2 class="text-center">Click here to sign up!</h2>
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    </div>
  </div>
<% end %>