config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  resources :users do
    resource :profile
    member do
      put :approve
      put :remove
    end
  end
  
  get 'friends', to: 'users#friends'
  
  resources :projects  
  
  resources :skills, except: [:destroy]
  
  resources :categories, except: [:destroy]
  
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :project_categories
  has_many :projects, through: :project_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @category = Category.new
  end
  
  def create
  @category = Category.new(category_params)
  if @category.save
    flash[:success] = "Category was created successfully"
    redirect_to categories_path
  else
    render 'new'
  end
  end
  
  def show
    @category = Category.find( params[:id] )
    @category_projects = @category.projects.paginate(page: params[:page], per_page: 5)
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !user_signed_in? || (user_signed_in? and !current_user.admin?)
    flash[:danger] = "Only admins can perform that action"
    redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class:'form-control', placeholder: "Enter category", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class:'btn btn-primary btn-lg' %>
    </div>
  </div> 
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit an category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">All Categories</h1>
<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="project-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.projects.count, "project") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>
<div align="center">
  <% if user_signed_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
    </br>
  <% end %>
  <%= will_paginate @category_projects %>
</div>
<%= render 'projects/project', obj: @category_projects %>
<div align="center">
  <%= will_paginate @category_projects %>
</div>