config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  devise_for :users
  
  get 'about', to: 'pages#about'
  
  resources :users do
    resource :profile
    member do
      put :approve
      put :remove
    end
  end
  
  get 'friends', to: 'users#friends'
  
  resources :projects  
  
  resources :skills, except: [:destroy]
  
  resources :categories, except: [:destroy]
  
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opensauce</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            OpenSauce
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">              
          <li><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
            <% else %>  
              <%= link_to "Log In", new_user_session_path, class: 'btn btn-default navbar-btn' %>
              <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <% end %>
          </div>
          <% if user_signed_in? %> 
            <ul class="nav navbar-nav navbar-right">
              <% if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Actions<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Add Category', new_category_path %></li>
                    <li><%= link_to 'Add Skill', new_skill_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to 'Create Admin User', users_path %></li>
                  </ul>
                </li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'New Project', new_project_path %></li>
                  <li><%= link_to 'All Projects', projects_path %></li>
                  <li><%= link_to 'Projects by Category', categories_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Your Projects', user_path(id: current_user.id ) %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'View Profile', user_path(id: current_user.id ) %></li>
                  <li><%= link_to 'Edit Profile', edit_user_profile_path(user_id: current_user.id ) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Security Settings', edit_user_registration_path %></li>
                </ul>
              </li>
              <li><%= link_to "Community", users_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
      <div class="container">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
      </div>
      
      <%= yield %>
    
  </body>
  
  <footer>
    <nav class="navbar navbar-default navbar-fixed-bottom custom-footer" role="navigation">
      <div class='container flash-container'>
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <div class="nav navbar-nav navbar-center">
              <ul class="nav navbar-nav navbar-center">
                <li><%= link_to "Privacy Policy", "/#" %></li>
                <li><%= link_to "Disclaimers", "/#" %></li>
                <li><%= link_to "Developers", "/#" %></li>
                <li><%= link_to "Contributions", "/#" %></li>
                <li><%= link_to "About", about_path %></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </div>
      </div>
    </nav>
  </footer>
</html>